### ISSUE TITLE
STARTTLS issue with aiosmtpd 1.4.2

### ISSUE THREAD

**Issue by lexitus** [YoRyan/mailrise#37]
I've been experiencing some issues with STARTTLS while using the latest Docker image (6415c43757780b5019dce526874a5acb03ad948013b175036bff909d7f5d555e)

Running with -vv gives the following output when trying to send a mail with STARTTLS set : 

```
[2022-12-18 11:55:43] INFO:mailrise.skeleton:Loaded configuration with 2 recipient(s)
[2022-12-18 11:55:43] INFO:mailrise.skeleton:TLS enabled and successfully initialized
[2022-12-18 11:55:43] DEBUG:asyncio:Using selector: EpollSelector
[2022-12-18 11:55:43] INFO:mail.log:Available AUTH mechanisms: LOGIN(builtin) PLAIN(builtin)
[2022-12-18 11:55:43] INFO:mail.log:Peer: ('127.0.0.1', 48256)
[2022-12-18 11:55:43] INFO:mail.log:('127.0.0.1', 48256) handling connection
[2022-12-18 11:55:43] DEBUG:mail.log:('127.0.0.1', 48256) << b'220 87a5a7182b69 Mailrise 0.0.post1.dev1+gbf98187'
[2022-12-18 11:55:43] INFO:mail.log:('127.0.0.1', 48256) EOF received
[2022-12-18 11:55:43] DEBUG:asyncio:Using selector: EpollSelector
[2022-12-18 11:55:43] INFO:mail.log:('127.0.0.1', 48256) Connection lost during _handle_client()
[2022-12-18 11:55:43] INFO:mail.log:('127.0.0.1', 48256) connection lost
[2022-12-18 11:59:59] INFO:mail.log:Available AUTH mechanisms: LOGIN(builtin) PLAIN(builtin)
[2022-12-18 11:59:59] INFO:mail.log:Peer: ('192.168.1.2', 60942)
[2022-12-18 11:59:59] INFO:mail.log:('192.168.1.2', 60942) handling connection
[2022-12-18 11:59:59] DEBUG:mail.log:('192.168.1.2', 60942) << b'220 87a5a7182b69 Mailrise 0.0.post1.dev1+gbf98187'
[2022-12-18 11:59:59] DEBUG:mail.log:_handle_client readline: b'EHLO bascule\r\n'
[2022-12-18 11:59:59] INFO:mail.log:('192.168.1.2', 60942) >> b'EHLO bascule'
[2022-12-18 11:59:59] DEBUG:mail.log:('192.168.1.2', 60942) << b'250-87a5a7182b69'
[2022-12-18 11:59:59] DEBUG:mail.log:('192.168.1.2', 60942) << b'250-SIZE 33554432'
[2022-12-18 11:59:59] DEBUG:mail.log:('192.168.1.2', 60942) << b'250-8BITMIME'
[2022-12-18 11:59:59] DEBUG:mail.log:('192.168.1.2', 60942) << b'250-SMTPUTF8'
[2022-12-18 11:59:59] DEBUG:mail.log:('192.168.1.2', 60942) << b'250-STARTTLS'
[2022-12-18 11:59:59] DEBUG:mail.log:('192.168.1.2', 60942) << b'250 HELP'
[2022-12-18 11:59:59] DEBUG:mail.log:_handle_client readline: b'STARTTLS\r\n'
[2022-12-18 11:59:59] INFO:mail.log:('192.168.1.2', 60942) >> b'STARTTLS'
[2022-12-18 11:59:59] DEBUG:mail.log:('192.168.1.2', 60942) << b'220 Ready to start TLS'
[2022-12-18 11:59:59] ERROR:asyncio:Fatal error: protocol.data_received() call failed.
protocol: <asyncio.sslproto.SSLProtocol object at 0x7fdcfb0b6210>
transport: <_SelectorSocketTransport fd=10 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 1001, in _read_ready__data_received
    self._protocol.data_received(data)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SSLProtocol' object has no attribute 'data_received'
[2022-12-18 11:59:59] ERROR:mail.log:('192.168.1.2', 60942) SMTP session exception
Traceback (most recent call last):
  File "/home/mailrise/.local/lib/python3.11/site-packages/aiosmtpd/smtp.py", line 895, in smtp_STARTTLS
    await waiter
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 1001, in _read_ready__data_received
    self._protocol.data_received(data)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SSLProtocol' object has no attribute 'data_received'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mailrise/.local/lib/python3.11/site-packages/aiosmtpd/smtp.py", line 728, in _handle_client
    await method(arg)
  File "/home/mailrise/.local/lib/python3.11/site-packages/aiosmtpd/smtp.py", line 899, in smtp_STARTTLS
    raise TLSSetupException() from error
aiosmtpd.smtp.TLSSetupException
[2022-12-18 11:59:59] INFO:mail.log:('192.168.1.2', 60942) connection lost
```

I *think* this is related to this fix in aiosmtpd : [https://github.com/aio-libs/aiosmtpd/commit/827f2321b7a926f3e8ba2aad6387b36c7c2e0b9a](https://github.com/aio-libs/aiosmtpd/commit/827f2321b7a926f3e8ba2aad6387b36c7c2e0b9a)

If I edit setup.cfg and build my own Docker image with that specific commit : 

```
install_requires =
    apprise==1.2.0
    #aiosmtpd==1.4.2
    aiosmtpd @ git+https://github.com/aio-libs/aiosmtpd.git@827f2321b7a926f3e8ba2aad6387b36c7c2e0b9a
    PyYAML==6.0
```

Then STARTTLS works as expected.

Looks like this fix will be in aiosmtpd 1.4.3, currently in rc. Just documenting this issue in case if get someone else 👍

**Comment by YoRyan** [comment]
Right, looks like an upstream bug. Thanks for documenting.
