### ISSUE TITLE
TLS disables authentication

### ISSUE THREAD

**Issue by bt90** [YoRyan/mailrise#41]
Config:
```yml
configs:
  pushover:
    urls:
      - pover://xxxxxxxxxxxxxxxx@yyyyyyyyyyyyyyyyy
tls:
  mode: starttls
  certfile: /etc/ssl/cert.pem
  keyfile: /etc/ssl/key.pem
smtp:
  hostname: nxdomain.info
  auth:
    basic:
      pushover: xxxxxxxxxxxxxxxxxxx
```

msmtp:
```
<-- 220 nxdomain.info Mailrise 0.0.post1.dev1+g8928d73
--> EHLO localhost
<-- 250-nxdomain.info
<-- 250-SIZE 33554432
<-- 250-8BITMIME
<-- 250-SMTPUTF8
<-- 250-STARTTLS
<-- 250 HELP
--> QUIT
<-- 221 Bye
msmtp: the server does not support authentication
```

Observation:  `250-AUTH LOGIN PLAIN` is missing

Log:
```
[2022-12-20 16:34:36] ERROR:asyncio:Fatal error: protocol.data_received() call failed.
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f5392c1b710>
transport: <_SelectorSocketTransport fd=10 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 1009, in _read_ready__data_received
    self._protocol.data_received(data)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SSLProtocol' object has no attribute 'data_received'
[2022-12-20 16:34:36] ERROR:mail.log:('172.18.0.1', 37216) SMTP session exception
Traceback (most recent call last):
  File "/home/mailrise/.local/lib/python3.11/site-packages/aiosmtpd/smtp.py", line 895, in smtp_STARTTLS
    await waiter
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 1009, in _read_ready__data_received
    self._protocol.data_received(data)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SSLProtocol' object has no attribute 'data_received'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mailrise/.local/lib/python3.11/site-packages/aiosmtpd/smtp.py", line 728, in _handle_client
    await method(arg)
  File "/home/mailrise/.local/lib/python3.11/site-packages/aiosmtpd/smtp.py", line 899, in smtp_STARTTLS
    raise TLSSetupException() from error
aiosmtpd.smtp.TLSSetupException
```

Steps to reproduce:

I generated a self-signed certifcate, changed the owner to the mailrise container user and mounted it:

```bash
openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 3650 -nodes -subj '/CN=nxdomain.info'
sudo chown 999:999 *.pem
```

```yml
  mailrise:
    container_name: mailrise
    image: yoryan/mailrise
    restart: always
    volumes:
      - ./mailrise.conf:/etc/mailrise.conf
      - ./cert.pem:/etc/ssl/cert.pem
      - ./key.pem:/etc/ssl/key.pem
```

**Comment by YoRyan** [comment]
Right, so I just pushed https://github.com/YoRyan/mailrise/commit/89305ba32324447c6853a297d1157bd803ad8575, which logs the arguments being passed to aiosmtpd. Here is what I get with your config:

`
[2022-12-21 18:32:34] DEBUG:mailrise.skeleton:Arguments for aiosmtpd: authenticator=Basic(1), auth_required=True, auth_require_tls=True, tls_context=<ssl.SSLContext object at 0x7f3b82511370>, ssl_context=None, require_starttls=False
`

The kicker here is `auth_require_tls=True`. I assumed that if you're running with TLS, you'll want your credentials encrypted. But this argument also [tells aiosmtpd not to send](https://github.com/aio-libs/aiosmtpd/blob/1.4.2/aiosmtpd/smtp.py#L820) the 250-AUTH message until the client has initiated an encrypted starttls session.

So you need to tell your client to initiate starttls before attempting authentication, or, alternatively, I can add a configuration option to set auth_require_tls to False. Not sure if that makes sense, though? Because then msmtp will probably send the credentials through cleartext...

**Comment by bt90** [comment]
I tried it again using curl:

```sh
curl -k --ssl -v smtp://localhost:25 --mail-rcpt pushover@mailrise.xyz --user 'pushover:xxxxxxxxxxxxx'  -T - <<<"Test"
```

```
*   Trying 127.0.0.1:25...
* Connected to localhost (127.0.0.1) port 25 (#0)
< 220 nxdomain.info Mailrise 0.0.post1.dev1+g8928d73
> EHLO proliant
< 250-nxdomain.info
< 250-SIZE 33554432
< 250-8BITMIME
< 250-SMTPUTF8
< 250-STARTTLS
< 250 HELP
> STARTTLS
< 220 Ready to start TLS
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.0 (OUT), TLS header, Unknown (21):
} [5 bytes data]
* TLSv1.3 (OUT), TLS alert, decode error (562):
} [2 bytes data]
* error:0A000126:SSL routines::unexpected eof while reading
* Closing connection 0
```

Note that curl is properly trying to upgrade the connection but fails due to an TLS error.

```
[2022-12-21 18:59:30] ERROR:asyncio:Fatal error: protocol.data_received() call failed.
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f3cdd7e7c50>
transport: <_SelectorSocketTransport fd=10 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 1009, in _read_ready__data_received
    self._protocol.data_received(data)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SSLProtocol' object has no attribute 'data_received'
[2022-12-21 18:59:30] ERROR:mail.log:('172.18.0.1', 46532) SMTP session exception
Traceback (most recent call last):
  File "/home/mailrise/.local/lib/python3.11/site-packages/aiosmtpd/smtp.py", line 895, in smtp_STARTTLS
    await waiter
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 1009, in _read_ready__data_received
    self._protocol.data_received(data)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SSLProtocol' object has no attribute 'data_received'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mailrise/.local/lib/python3.11/site-packages/aiosmtpd/smtp.py", line 728, in _handle_client
    await method(arg)
  File "/home/mailrise/.local/lib/python3.11/site-packages/aiosmtpd/smtp.py", line 899, in smtp_STARTTLS
    raise TLSSetupException() from error
aiosmtpd.smtp.TLSSetupException
```

**Comment by bt90** [comment]
Hmm https://gitlab.com/mailman/mailman/-/issues/936

**Comment by bt90** [comment]
Coincidentally, the fixed version was released 4 hours ago.

https://github.com/aio-libs/aiosmtpd/releases/tag/1.4.3

**Comment by YoRyan** [comment]
Right, starttls was broken in the last stable aiosmtpd. #37 reported it
just the other day. I'll upgrade versions ASAP.

(Glad to see that it's finally out; I've been waiting on the new unthreaded
controller API.)

**Comment by YoRyan** [comment]
Right, starttls was broken in the last stable aiosmtpd. #37 reported it just the other day. I'll upgrade versions ASAP.

(Glad to see that it's finally out; I've been waiting on the new unthreaded controller API.)

**Comment by YoRyan** [comment]
Upgrade complete. Please let me know if all is well with starttls. Cheers!

**Comment by bt90** [comment]
STARTTLS works properly now 🎉 

I also tried `onconnect` but that doesn't seem to work. A TLS connection is established by curl but the server doesn't announce that it requires authentication:

```bash
curl -k -s -v smtps://localhost:587 --mail-rcpt pushover@mailrise.xyz --user 'pushover:xxxxxxxxxxx'  -T - <<<"Test"
```

```
< 220 nxdomain.info Mailrise 0.0.post1.dev1+g5d58a83
> EHLO proliant
< 250-nxdomain.info
< 250-SIZE 33554432
< 250-8BITMIME
< 250-SMTPUTF8
< 250 HELP
> MAIL FROM:<>
< 530 5.7.0 Authentication required
> QUIT
< 221 Bye
```

Config:

```yml
configs:
  pushover:
    urls:
      - pover://xxxxxxxxxxxxxxxx@yyyyyyyyyyyyyyyyyyy
tls:
  mode: onconnect
  certfile: /etc/ssl/cert.pem
  keyfile: /etc/ssl/key.pem
smtp:
  hostname: nxdomain.info
  auth:
    basic:
      pushover: xxxxxxxxxxxxxxxx
```

**Comment by YoRyan** [comment]
Misinterpreted the use of `auth_require_tls`. In the on-connect mode, aiosmtpd isn't aware of the TLS wrapper, so that argument should be set to False.

Should be fixed with https://github.com/YoRyan/mailrise/commit/80384738d2e50558fd130d3075ef39ac70a2c9c8. Thanks again for all your help testing these TLS use-cases.

**Comment by bt90** [comment]
Works 👍 

> Thanks again for all your help testing these TLS use-cases.

No, I thank *you* for developing this nice piece of tech 😉
