### ISSUE TITLE
Cannot start mailrise docker container

### ISSUE THREAD

**Issue by maxxar79** [YoRyan/mailrise#89]
I cant get this running after upgrade to latest version, tried to revert back to old version but can't get it work there either.
Tried everything i'll think. what am i doing wrong?

mailrise.conf file i'm using look like this

configs:
  discord:
    urls:
      - discord://2308599788026707641/sdfnsdsdslkslsfalsfsdrlfsdulfsf

docker-compose running 

version: '3.8'
services:
  mailrise:
    image: yoryan/mailrise:latest
    container_name: mailrise
    ports:
      - 8025:8025
    volumes:
      - ./mailrise/mailrise.conf:/etc/mailrise.conf
    restart: unless-stopped

Logged problem

Traceback (most recent call last):

  File "/home/mailrise/.local/bin/mailrise", line 8, in <module>

    sys.exit(run())

             ^^^^^

  File "/home/mailrise/.local/lib/python3.12/site-packages/mailrise/skeleton.py", line 171, in run

    main(sys.argv[1:])

  File "/home/mailrise/.local/lib/python3.12/site-packages/mailrise/skeleton.py", line 162, in main

    controller.begin()

  File "/home/mailrise/.local/lib/python3.12/site-packages/aiosmtpd/controller.py", line 370, in begin

    srv: AsyncServer = self.loop.run_until_complete(self.server_coro)

                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 664, in run_until_complete

    return future.result()

           ^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1505, in create_server

    infos = await tasks.gather(*fs)

            ^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1437, in _create_server_getaddrinfo

    infos = await self._ensure_resolved((host, port), family=family,

            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1433, in _ensure_resolved

    return await loop.getaddrinfo(host, port, family=family, type=type,

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 878, in getaddrinfo

    return await self.run_in_executor(

                 ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 840, in run_in_executor

    executor.submit(func, *args), loop=self)

    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 179, in submit

    self._adjust_thread_count()

  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 202, in _adjust_thread_count

    t.start()

  File "/usr/local/lib/python3.12/threading.py", line 971, in start

    _start_new_thread(self._bootstrap, ())

RuntimeError: can't start new thread

**Comment by maxxar79** [comment]
Installed mailrise with the same config on another virtual machine without problems must be some local docker problem.

**Comment by YoRyan** [comment]
Glad it worked out!
