### ISSUE TITLE
SMTP session exception - KeyError: 'multipart/related'

### ISSUE THREAD

**Issue by janost** [YoRyan/mailrise#9]
Great project, thanks for your work!

I'm experiencing an issue when I'm trying to use mailrise as an SMTP->Telegram gateway. I'd like mailrise to forward emails with attached images from my security cameras to a Telegram group conversation. I'm using Blue Iris as an NVR software and mailrise is running on the same machine as BI on windows x64 with Python 3.9.7.

```
configs:
  telegram:
    urls:
      - tgram://BOTID/CHATID/?image=Yes
```

When sending an email I'm experiencing the following error:
```
[2021-09-02 22:42:41] INFO:mailrise.skeleton:Loaded configuration with 1 recipient(s)
[2021-09-02 22:42:41] INFO:mail.log:Available AUTH mechanisms: LOGIN(builtin) PLAIN(builtin)
[2021-09-02 22:42:41] INFO:mail.log:Peer: ('::1', 62137, 0, 0)
[2021-09-02 22:42:41] INFO:mail.log:('::1', 62137, 0, 0) handling connection
[2021-09-02 22:42:41] INFO:mail.log:('::1', 62137, 0, 0) EOF received
[2021-09-02 22:42:41] INFO:mail.log:('::1', 62137, 0, 0) Connection lost during _handle_client()
[2021-09-02 22:42:41] INFO:mail.log:('::1', 62137, 0, 0) connection lost
[2021-09-02 22:42:46] INFO:mail.log:Available AUTH mechanisms: LOGIN(builtin) PLAIN(builtin)
[2021-09-02 22:42:46] INFO:mail.log:Peer: ('127.0.0.1', 62141)
[2021-09-02 22:42:46] INFO:mail.log:('127.0.0.1', 62141) handling connection
[2021-09-02 22:42:46] INFO:mail.log:('127.0.0.1', 62141) >> b'HELO nvr.local'
[2021-09-02 22:42:46] INFO:mail.log:('127.0.0.1', 62141) >> b'MAIL FROM:<blueiris@nvr>'
[2021-09-02 22:42:46] INFO:mail.log:('127.0.0.1', 62141) sender: blueiris@nvr
[2021-09-02 22:42:46] INFO:mail.log:('127.0.0.1', 62141) >> b'RCPT TO:<telegram@mailrise.xyz>'
[2021-09-02 22:42:46] INFO:mailrise.skeleton:Accepted recipient: telegram@mailrise.xyz
[2021-09-02 22:42:46] INFO:mail.log:('127.0.0.1', 62141) recip: telegram@mailrise.xyz
[2021-09-02 22:42:46] INFO:mail.log:('127.0.0.1', 62141) >> b'DATA'
[2021-09-02 22:42:47] ERROR:mail.log:('127.0.0.1', 62141) SMTP session exception
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\aiosmtpd\smtp.py", line 728, in _handle_client
    await method(arg)
  File "C:\Python39\lib\site-packages\aiosmtpd\smtp.py", line 1438, in smtp_DATA
    status = await self._call_handler_hook('DATA')
  File "C:\Python39\lib\site-packages\aiosmtpd\smtp.py", line 465, in _call_handler_hook
    status = await hook(self, self.session, self.envelope, *args)
  File "C:\Python39\lib\site-packages\mailrise\smtp.py", line 113, in handle_DATA
    notification = parsemessage(message)
  File "C:\Python39\lib\site-packages\mailrise\smtp.py", line 200, in parsemessage
    body = body_part.get_content().strip()
  File "C:\Python39\lib\email\message.py", line 1096, in get_content
    return content_manager.get_content(self, *args, **kw)
  File "C:\Python39\lib\email\contentmanager.py", line 25, in get_content
    raise KeyError(content_type)
KeyError: 'multipart/related'
[2021-09-02 22:42:47] INFO:mail.log:('127.0.0.1', 62141) EOF received
[2021-09-02 22:42:47] INFO:mail.log:('127.0.0.1', 62141) Connection lost during _handle_client()
[2021-09-02 22:42:47] INFO:mail.log:('127.0.0.1', 62141) connection lost
```

Any help would be appreciated.

**Comment by YoRyan** [comment]
It looks like Blue Iris is sending MIME multipart messages, which [can't be decoded](https://docs.python.org/3/library/email.contentmanager.html#email.contentmanager.get_content) by Python's email parser. The quick fix would be to discard the exception and simply send the notification without a body. But depending on the layout of the message, that could mean losing out on critical information.

Would it be possible to get a raw sample message sent by Blue Iris? Feel free to redact any sensitive information. (Especially any binary attachments. You can just omit their data; what's important is where they are located.)

**Comment by gary-sargent** [comment]
@YoRyan I have the same issue? What do you need?

The headers have:

`Subject: =?utf-8?B?Qmx1ZSBJcmlzIFBlb3BsZTo4NyUsUGVvcGxlOjg2JSxwZXJz?=
	=?utf-8?B?b246NzklLHBlcnNvbjo3MyUgQWxlcnQ=?=
MIME-Version: 1.0
Content-Type: multipart/related;
	boundary="7b7c61d87406d29c2ad7260600388c35"
`

**Comment by YoRyan** [comment]
Could you attach the contents of the entire email? You may redact information, but I need to see the boundaries between all the data.

**Comment by gary-sargent** [comment]
Hi @YoRyan I've emailed you an example.

**Comment by YoRyan** [comment]
Thanks to @gary-sargent's generously donated sample, these kinds of emails should be working now!
